server {
    listen 80;
    server_name your_domain.com www.your_domain.com;

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/andrey/site/app.sock;
    }

    location /static/ {
        alias /home/andrey/site/static/;
    }

    # Настройки для Certbot появятся здесь автоматически после запуска sudo certbot --nginx
}